api: "sncloud" #  set either sambastudio or sncloud

embedding_model: 
    "type": "cpu" # set either sambastudio or cpu
    "batch_size": 1 #set depending of your endpoint configuration (1 if CoE embedding expert)
    "coe": True #set true if using Sambastudio embeddings in a CoE endpoint 
    "select_expert": "e5-mistral-8b-instruct" #set if using SambaStudio CoE embedding expert

llm:
    "temperature": 0.01
    "max_tokens_to_generate": 500
    "top_p": 1
    "do_sample": false
    "coe": True #set as true if using Sambastudio CoE endpoint
    "select_expert": "llama3-405b" #set if using sncloud, SambaStudio CoE llm expert
    #sncloud CoE expert name -> "llama3-405b"

retrieval:
    "chunk_size": 1200
    "chunk_overlap": 240
    "db_type": "chroma"
    "k_retrieved_documents": 3
    "score_treshold": 0.3

web_crawling:
    "max_scraped_websites": 20
    "excluded_links":
        - 'facebook.com'
        - 'twitter.com'
        - 'instagram.com'
        - 'linkedin.com'
        - 'telegram.me'
        - 'reddit.com'
        - 'whatsapp.com'
        - 'wa.me' 

prod_mode: False
additional_env_vars:
  - SERPAPI_API_KEY

extra_loaders:
    - "pdf"
